name: Run tests and deploy Allure report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB_AUTH=${{ secrets.POSTGRES_DB_AUTH }}" >> .env
          echo "POSTGRES_DB_UNIVERSITY=${{ secrets.POSTGRES_DB_UNIVERSITY }}" >> .env
          echo "UNIVERSITY_SERVICE_INTERNAL_URL=${{ secrets.UNIVERSITY_SERVICE_INTERNAL_URL }}" >> .env
          echo "UNIVERSITY_SERVICE_API_URL=${{ secrets.UNIVERSITY_SERVICE_API_URL }}" >> .env
          echo "AUTH_SERVICE_INTERNAL_URL=${{ secrets.AUTH_SERVICE_INTERNAL_URL }}" >> .env
          echo "AUTH_SERVICE_API_URL=${{ secrets.AUTH_SERVICE_API_URL }}" >> .env

      - name: Start API services
        run: docker compose up -d

      - name: Run Alembic migrations
        run: |
          docker compose run --rm auth alembic upgrade head
          docker compose run --rm university alembic upgrade head


      - name: Wait for APIs to be ready
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat
          echo "Waiting for auth service (port 8000)..."
          while ! nc -zv localhost 8000; do sleep 2; done
          echo "Waiting for university service (port 8001)..."
          while ! nc -zv localhost 8001; do sleep 2; done
          echo "Both APIs are ready!"

      - name: Run tests in Docker
        run: docker compose run --rm tests

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          keep_files: false